config/routes.rb
Sample::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy] 

  match "/signup", :to => "users#new"

  match "/signin",  :to => "sessions#new"
  match "/signout", :to => "sessions#destroy"
  match "/home", :to => "pages#home"
  match "/contact", :to => "pages#contact"
  match "/about", :to => "pages#about"
  match "/help", :to => "pages#help"
  
  root :to => "pages#home" 
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name
  field :email
  index :email, unique: true
  field :encrypted_password
  field :salt

  # Ruby method, creates virtual attribute
  attr_accessor :password
  
  # Rails method for mass assignment
  attr_accessible :name, :email, :password, :password_confirmation

  before_save :encrypt_password

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,     :presence     => true,
                       :length       => { :maximum => 50  }
  validates :email,    :presence     => true,
                       :format       => { :with => email_regex },
                       :uniqueness   => { :case_sensitive => false }
  
  # Automatically create the virtual attribute 'password_confirmation'.                     
  validates :password, :confirmation => true,
                       :presence     => true,
                       :length       => { :within => 6..40 }

  def self.find_by_email(email)
    where(:email => email).first
  end

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    (user && user.has_password?(submitted_password)) ? user : nil
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie.salt) ? user :nil
  end

private

  def encrypt_password
    self.salt = make_salt unless has_password?(password)
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "Home"
  end

  def contact
  	@title = "Contact"
    drop_breadcrumb("Contact")
  end

  def about
  	@title = "About"
    drop_breadcrumb("About")
  end

  def help
  	@title = "Help"
    drop_breadcrumb("Help")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
    drop_breadcrumb("Sign in")
  end

  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      drop_breadcrumb("Sign in")
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
    drop_breadcrumb("Sign up")
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign up"      
      drop_breadcrumb("Sign up")
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Sample App Revision"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
	end

  def notice_message
    flash_messages = []

    flash.each do |type, message|
      type = :success if type == :notice
      text = content_tag(:div, link_to("x", "#", :class => "close") + message, :class => "alert-message #{type} fade in", "data-alert" => "alert")
      flash_messages << text if message
    end

    flash_messages.join("\n").html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user || user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => h(user.name),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/layouts/_footer.html.haml
%footer
  .container
    %p.links
      = link_to "About", about_path
      |
      = link_to "Contact", contact_path
      |
      %a{:href => "http://news.railstutorial.org/"} News
      |
      %a{:href => "http://www.railstutorial.org/"} Rails Tutorial

app/views/layouts/_header.html.haml
.topbar
  .topbar-inner
    .container
      %a.brand{ :href => "/" } Sample App v2
      %ul.nav
        %li.active
          = link_to "Home", root_path
        %li
          = link_to "Help", help_path
        %li
          = link_to "Sign in", signin_path

app/views/layouts/application.html.haml
!!!html
%head
  %title 
    = title
  = stylesheet_link_tag :application
  = javascript_include_tag :application
  = csrf_meta_tags
  
%body
  = render "layouts/header"
  .container
    = render_breadcrumb    
    = notice_message
    .content.round
      = yield
    = render "layouts/footer"
    = debug(params) if Rails.env.development?

app/views/pages/about.html.haml
%p
  %a{:href => "http://railstutorial.org/"} Ruby on Rails Tutorial
  is a project to make a book and screencasts to teach web development
  with 
  %a{ :href => "http://rubyonrails.org/"} Ruby on Rails. This
  is the sample application for the tutorial.

app/views/pages/contact.html.haml
%p
  Contact Ruby on Rails Tutorial about the sample app at the
  %a{:href => "http://railstutorial.org/feedback"} feedback page.

app/views/pages/help.html.haml
%p
  Get help on Ruby on Rails Tutorial at the
  %a{:href => "http://railstutorial.org/help"} Rails Tutorial help page.
  To get help on this sample app, see the
  %a{:href => "http://railstutorial.org/book"} Rails Tutorial book.

app/views/pages/home.html.haml
%p
  This is the home page for the
  %a{:href => "http://railstutorial.org/"} Ruby on Rails Tutorial sample application.

= link_to "Sign up now!", signup_path, :class => "signup btn primary round"

app/views/users/new.html.haml
.page-header
  %h1 Sign up
= simple_form_for @user, :wrapper => :inline do |f|
  - if f.error_notification
    .alert-message.warning.fade.in{"data-alert" =>"alert"}
      %a.close{ :href => "#" } ×
      %p
        = f.error_notification
  .inputs
    = f.input :name
    = f.input :email
    = f.input :password
    = f.input :password_confirmation, {:label => "Confirmation" }
  .actions
    = f.submit "Sign up", :class => 'btn primary'

app/views/users/show.html.haml
.row
  .span8
    %h1
      = gravatar_for @user, :size => 50
      = @user.name

  .span3
    %strong Name
    = @user.name
    %br
    %strong URL
    = link_to user_path(@user), @user
    